### PR TITLE
Added Fibaro Flood Sensor

### PR DESCRIPTION
**Pull request by leoneleone**
else if (s.type == "com.fibaro.floodSensor")
				service = {controlService: new Service.LeakSensor(s.name), characteristics: [Characteristic.LeakDetected]};

### CODE REVIEW

**Comment by ilcato** [comment]
Does it works?

**Comment by leoneleone** [comment]
I'm testing it now.

I think I have to add some code to among the UINT8 format for Characteristic.LeakDetected.
I expected it to be a BOOL value but it isn't. 

Where should I add this to the code?

According to HAP-NodeJS HomeKitTypes :
/**
 * Characteristic "Leak Detected"
 */

Characteristic.LeakDetected = function() {
  Characteristic.call(this, 'Leak Detected', '00000070-0000-1000-8000-0026BB765291');
  this.setProps({
    format: Characteristic.Formats.UINT8,
    perms: [Characteristic.Perms.READ, Characteristic.Perms.NOTIFY]
  });
  this.value = this.getDefaultValue();
};

inherits(Characteristic.LeakDetected, Characteristic);

Characteristic.LeakDetected.UUID = '00000070-0000-1000-8000-0026BB765291';

// The value property of LeakDetected must be one of the following:
Characteristic.LeakDetected.LEAK_NOT_DETECTED = 0;
Characteristic.LeakDetected.LEAK_DETECTED = 1;

**Comment by leoneleone** [comment]
Fore some reason I my Fibaro branded leak sensors don't initialise. I have some Aeotec Leak Sensors and they initialise fine.

Do I need to add the Fibaro type "com.fibaro.FGFS101" ??
According to HomeCenter the Fibaro flood sensors are type:
FGFS101 Flood Sensor EU

but i'm not sure how to add this correctly so they show up in HomeKit

I've tried:
        else if (s.type == "com.fibaro.FGFS101" || s.type == "com.fibaro.floodSensor")
            service = {controlService: new Service.LeakSensor(s.name), characteristics: [Characteristic.LeakDetected]};

but the Fibaro flood sensors down't show up. Just the other Aeotec Leak Sensors.

Any ideas?

**Comment by leoneleone** [comment]
Actually everything seems to be working and all my sensors show up.

I will test functionality then get back to you with an updated pull request

**Comment by leoneleone** [comment]
No functionality. We have to add code to manage the LeakDetected Characteristic. 

I'm not familiar with to code for the Fibaro end of things. And the values must not be BOOL in homebridge, otherwise the sensors show up, but either show N/A for the value, or in ios10 HomeKit the sensors and constantly giving "no response"

**Comment by leoneleone** [comment]
Any ideas?

**Pull request closed without merging**
