### PR TITLE
Expose Model, Serial value from HC2 API in AccessoryInformation

### PR DESCRIPTION
**Pull request by lboue**
Expose Model, Serial value from HC2 API in AccessoryInformation

### CODE REVIEW

**Comment by ilcato** [comment]
A doubt: why do you remove com.fibaro from the model name?

**Comment by ilcato** [comment]
Since the serial number is not populated, try to include the name as in the PR #116.

**Comment by ilcato** [comment]
@lboue, are you able to resolve the conflicts ?

**Comment by ilcato** [comment]
@lboue, can we close this because of #150 ?

**Comment by lboue** [comment]
Sure.

**Pull request closed without merging**
