### PR TITLE
Battery level support

### PR DESCRIPTION
**Pull request by hovorkap**
Should resolve https://github.com/ilcato/homebridge-Fibaro-HC2/issues/112

### CODE REVIEW

**Comment by lboue** [comment]
Hello,

Thanks for this change, I was hopping to make it work since a long time. It seems to work because I am getting a low battery alarm on a device 👍.

But I can see an error in starting log:

```
[2019-4-26 23:58:15] Loaded plugin: homebridge-fibaro-hc2
[2019-4-26 23:58:15] Registering platform 'homebridge-fibaro-hc2.FibaroHC2'
...
[2019-4-26 23:58:23] Loading 6 platforms...
...
[2019-4-26 23:58:23] [FibaroHC2] Initializing FibaroHC2 platform...
[2019-4-26 23:58:23] [FibaroHC2] Configured Accessory:  Guirlande
[2019-4-26 23:58:23] [FibaroHC2] Configured Accessory:  Freebox 
[2019-4-26 23:58:23] [FibaroHC2] Configured Accessory:  VR Sejour
[2019-4-26 23:58:23] [FibaroHC2] Configured Accessory:  Volet Salle de jeu
[2019-4-26 23:58:23] [FibaroHC2] Configured Accessory:  Volet bureau
[2019-4-26 23:58:23] [FibaroHC2] Configured Accessory:  Lampe Etagere
[2019-4-26 23:58:23] [FibaroHC2] Configured Accessory:  PC
[2019-4-26 23:58:23] [FibaroHC2] Configured Accessory:  Multiprise
[2019-4-26 23:58:23] [FibaroHC2] Configured Accessory:  Ecran PC
[2019-4-26 23:58:23] [FibaroHC2] Configured Accessory:  Multiprise P5
[2019-4-26 23:58:23] [FibaroHC2] Configured Accessory:  Multiprise - P6
[2019-4-26 23:58:23] [FibaroHC2] Configured Accessory:  VR Salon
[2019-4-26 23:58:23] [FibaroHC2] Configured Accessory:  Seche-serviettes
[2019-4-26 23:58:23] [FibaroHC2] Configured Accessory:  VR Cuisine
[2019-4-26 23:58:23] [FibaroHC2] Configured Accessory:  VR Escalier
[2019-4-26 23:58:23] [FibaroHC2] Configured Accessory:  Detect. Fumee etage
[2019-4-26 23:58:23] [FibaroHC2] Configured Accessory:  Temp Couloir
[2019-4-26 23:58:23] [FibaroHC2] Configured Accessory:  Detecteur fuite
[2019-4-26 23:58:23] [FibaroHC2] Configured Accessory:  Temp cellier
[2019-4-26 23:58:23] [FibaroHC2] Configured Accessory:  VR Parents Etage
[2019-4-26 23:58:23] [FibaroHC2] Configured Accessory:  Volet Chambre Coline
[2019-4-26 23:58:23] [FibaroHC2] Configured Accessory:  Lampe couloir étage
[2019-4-26 23:58:23] [FibaroHC2] Configured Accessory:  Lampe Ch. parents
[2019-4-26 23:58:23] [FibaroHC2] didFinishLaunching. 
[2019-4-26 23:58:24] [FibaroHC2] Loading accessories 
[2019-4-26 23:58:24] [FibaroHC2] Added/changed accessory:  Guirlande
[2019-4-26 23:58:24] [FibaroHC2] Added/changed accessory:  Freebox mini
[2019-4-26 23:58:24] [FibaroHC2] Added/changed accessory:  VR Sejour
[2019-4-26 23:58:24] [FibaroHC2] Added/changed accessory:  Volet Salle de jeu
[2019-4-26 23:58:24] [FibaroHC2] Added/changed accessory:  Volet bureau
[2019-4-26 23:58:24] [FibaroHC2] Added/changed accessory:  Lampe Etagere
[2019-4-26 23:58:24] [FibaroHC2] Added/changed accessory:  PC
[2019-4-26 23:58:25] [FibaroHC2] Added/changed accessory:  Multiprise
[2019-4-26 23:58:26] [FibaroHC2] Added/changed accessory:  Ecran PC
[2019-4-26 23:58:26] [FibaroHC2] Added/changed accessory:  Multiprise P5
[2019-4-26 23:58:26] [FibaroHC2] Added/changed accessory:  Multiprise - P6
[2019-4-26 23:58:26] [FibaroHC2] Added/changed accessory:  VR Salon
[2019-4-26 23:58:26] [FibaroHC2] Added/changed accessory:  Seche-serviettes
[2019-4-26 23:58:26] [FibaroHC2] Added/changed accessory:  VR Cuisine
[2019-4-26 23:58:26] [FibaroHC2] Added/changed accessory:  VR Escalier
[2019-4-26 23:58:26] [FibaroHC2] Error getting data from Home Center:  Error: Cannot add a Service with the same UUID '00000096-0000-1000-8000-0026BB765291' and subtype '170----' as another Service in this Accessory.
    at PlatformAccessory.addService (/usr/lib/node_modules/homebridge/lib/platformAccessory.js:55:15)
    at ShadowAccessory.addNewServices (/tmp/homebridge-Fibaro-HC2-shadows-factory/src/shadows.ts:93:20)
    at FibaroHC2.addAccessory (/tmp/homebridge-Fibaro-HC2-shadows-factory/src/index.ts:253:19)
    at LoadAccessories.devices.map (/tmp/homebridge-Fibaro-HC2-shadows-factory/src/index.ts:198:10)
    at Array.map (<anonymous>)
    at FibaroHC2.LoadAccessories (/tmp/homebridge-Fibaro-HC2-shadows-factory/src/index.ts:195:11)
    at fibaroClient.getScenes.then.then (/tmp/homebridge-Fibaro-HC2-shadows-factory/src/index.ts:158:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Could you help me to fix it?

Regards,
Ludovic

**Comment by hovorkap** [comment]
I see, it looks like it tries to add the battery service twice
Battery Service | 00000096-0000-1000-8000-0026BB765291.

I'll try to reproduce while mocking using your device data.

**Comment by hovorkap** [comment]
@lboue I can see the device with id 169 is a parent device and under normal circumstances these generic zwave parents are not visible. As per current hc2 plugin implementation it skips hidden devices. This needs to be fixed to correctly merge accessory services while not adding duplicates.

As a workaround, mark the 169 as hidden in HC2 and maybe all other zwave parent devices as well.

Cheers,
Petr

**Comment by lboue** [comment]
@hovorkap I marked the 169 as hidden in HC2 but I doesn't work. I still have the issue.
```
[2019-4-27 14:14:36] [FibaroHC2] Added/changed accessory:  VR Escalier
[2019-4-27 14:14:36] [FibaroHC2] Error getting data from Home Center:  Error: Cannot add a Service with the same UUID '00000096-0000-1000-8000-0026BB765291' and subtype '170----' as another Service in this Accessory.
    at PlatformAccessory.addService (/usr/lib/node_modules/homebridge/lib/platformAccessory.js:55:15)
    at ShadowAccessory.addNewServices (/tmp/homebridge-Fibaro-HC2-shadows-factory/src/shadows.ts:93:20)
    at FibaroHC2.addAccessory (/tmp/homebridge-Fibaro-HC2-shadows-factory/src/index.ts:253:19)
    at LoadAccessories.devices.map (/tmp/homebridge-Fibaro-HC2-shadows-factory/src/index.ts:198:10)
    at Array.map (<anonymous>)
    at FibaroHC2.LoadAccessories (/tmp/homebridge-Fibaro-HC2-shadows-factory/src/index.ts:195:11)
    at fibaroClient.getScenes.then.then (/tmp/homebridge-Fibaro-HC2-shadows-factory/src/index.ts:158:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I also marked the 172 as hidden in HC2 with is the _heatDetector_ from the same parent device.

`{"id":172,"name":"Alerte Couloir","roomID":207,"type":"com.fibaro.heatDetector","baseType":"com.fibaro.lifeDangerSensor","enabled":true,"visible":false,"isPlugin":false,"parentId":169,"remoteGatewayId":0,"interfaces":["battery","fibaroBreach","zwave","zwaveWakeup"],"properties":{"batteryLevel":10,"parameters":[{"id":1,"size":1,"value":2},{"id":2,"size":1,"value":0},{"id":3,"size":1,"value":0},{"id":4,"size":1,"value":0},{"id":10,"size":1,"value":0},{"id":11,"size":2,"value":255},{"id":12,"size":2,"value":0},{"id":13,"size":1,"value":0},{"id":14,"size":1,"value":15},{"id":20,"size":2,"value":1},{"id":21,"size":1,"value":10},{"id":30,"size":1,"value":55},{"id":31,"size":2,"value":1},{"id":32,"size":2,"value":180}],"pollingTimeSec":0,"wakeUpTime":21600,"zwaveCompany":"Fibargroup","zwaveInfo":"3,4,5","zwaveVersion":"3.2","batteryLowNotification":"true","configured":true,"dead":"false","defInterval":"0","deviceControlType":"0","deviceIcon":"88","emailNotificationID":"0","emailNotificationType":"0","endPointId":"0","lastBreached":"0","liliOffCommand":"","liliOnCommand":"","log":"En attente du réveil","logTemp":"TxtGreen","manufacturer":"","markAsDead":"true","maxInterval":"0","minInterval":"0","model":"","nodeId":"15","parametersTemplate":"566","productInfo":"1,15,12,2,16,2,3,2","pushNotificationID":"0","pushNotificationType":"0","remoteGatewayId":"0","saveLogs":"true","serialNumber":"","smsNotificationID":"0","smsNotificationType":"0","stepInterval":"0","useTemplate":"true","userDescription":"","value":"false"},"actions":{"forceArm":0,"meetArmConditions":0,"reconfigure":0,"setArmed":1,"setInterval":1},"created":1547827756,"modified":1547827756,"sortOrder":79}`

Any idea?

Regards
Ludovic

**Comment by hovorkap** [comment]
@lboue I've found the problem, I forgot to pass device name in BatteryService() ctor, should be fine now. Can you please try?

cheers,
Petr

**Comment by lboue** [comment]
@hovorkap Could you give me the link to the file so I can try? I didn't find it.

**Comment by lboue** [comment]
I did the test against this commit https://github.com/hovorkap/homebridge-Fibaro-HC2/commit/1ba5d8d0cf0f4782bac891783bf5974689fec35e and it is working fine. No more error 👍

**Comment by hovorkap** [comment]
Well, that is work in progress, but rebased on the battery level branch.

**Comment by hovorkap** [comment]
>@hovorkap Could you give me the link to the file so I can try? I didn't find it.

@lboue still the same branch, I did a force push. You can hard reset to battery-level branch

**Comment by lboue** [comment]
Hello,

Sorry for this late reply. I was busy this week. 
I did a fresh install from 'remotes/origin/battery-level' branch and it's works fine. No error:
```
pi@raspberrypi:/tmp $ git clone https://github.com/hovorkap/homebridge-Fibaro-HC2.git
Clonage dans 'homebridge-Fibaro-HC2'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 1347 (delta 3), reused 9 (delta 3), pack-reused 1338
Réception d'objets: 100% (1347/1347), 417.90 KiB | 0 bytes/s, fait.
Résolution des deltas: 100% (955/955), fait.


pi@raspberrypi:/tmp $ cd homebridge-Fibaro-HC2
pi@raspberrypi:/tmp/homebridge-Fibaro-HC2 $ git branch -a
* master
  remotes/origin/ES6
  remotes/origin/HEAD -> origin/master
  remotes/origin/accessory-info
  remotes/origin/battery-level
  remotes/origin/master
  remotes/origin/plugin-2.0
  remotes/origin/shadows-factory
pi@raspberrypi:/tmp/homebridge-Fibaro-HC2 $  git checkout remotes/origin/battery-level
Note : extraction de 'remotes/origin/battery-level'.

HEAD est maintenant sur 3e9f2e9... Battery level support
pi@raspberrypi:/tmp/homebridge-Fibaro-HC2 $ 
pi@raspberrypi:/tmp/homebridge-Fibaro-HC2 $ git branch 
* (HEAD détachée sur origin/battery-level)
  master
pi@raspberrypi:/tmp/homebridge-Fibaro-HC2 $ git log
commit 3e9f2e92d3101281dd5440096cfe4a7fe9e3a9d0
Author: Petr Hovorka <hovorkap>
Date:   Sun Apr 7 00:24:08 2019 +0200

    Battery level support

commit 53c65b55cc2b70ad560ea015b811beb4e3742fc8
Merge: 2ad4eb1 415dece
Author: ilcato <ilcato@yahoo.com>
Date:   Sat Apr 27 08:09:19 2019 +0200

    Merge pull request #149 from hovorkap/accessory-info
    
    Accessory information - Manufacturer, model, serial and firmware

pi@raspberrypi:/tmp/homebridge-Fibaro-HC2 $ sudo npm install -g .   
+ homebridge-fibaro-hc2@2.2.2
added 50 packages from 61 contributors in 28.666s


pi@raspberrypi:~ $ tail -150f /home/pi/.pm2/logs/homebridge-out-0.log
[2019-5-4 20:52:21] Loaded config.json with 3 accessories and 6 platforms.
[2019-5-4 20:52:21] ---
..
[2019-5-4 20:52:27] Loaded plugin: homebridge-fibaro-hc2
[2019-5-4 20:52:27] Registering platform 'homebridge-fibaro-hc2.FibaroHC2'
[2019-5-4 20:52:27] ---
[2019-5-4 20:52:44] [FibaroHC2] Initializing FibaroHC2 platform...
[2019-5-4 20:52:44] [FibaroHC2] Configured Accessory:  Guirlande
[2019-5-4 20:52:44] [FibaroHC2] Configured Accessory:  Freebox mini
[2019-5-4 20:52:44] [FibaroHC2] Configured Accessory:  VR Sejour
[2019-5-4 20:52:44] [FibaroHC2] Configured Accessory:  Volet Salle de jeu
[2019-5-4 20:52:44] [FibaroHC2] Configured Accessory:  Volet bureau
[2019-5-4 20:52:44] [FibaroHC2] Configured Accessory:  Lampe Etagere
[2019-5-4 20:52:44] [FibaroHC2] Configured Accessory:  PC
[2019-5-4 20:52:44] [FibaroHC2] Configured Accessory:  Multiprise
[2019-5-4 20:52:44] [FibaroHC2] Configured Accessory:  Ecran PC
[2019-5-4 20:52:44] [FibaroHC2] Configured Accessory:  Multiprise P5
[2019-5-4 20:52:44] [FibaroHC2] Configured Accessory:  Multiprise - P6
[2019-5-4 20:52:44] [FibaroHC2] Configured Accessory:  VR Salon
[2019-5-4 20:52:44] [FibaroHC2] Configured Accessory:  Seche-serviettes
[2019-5-4 20:52:44] [FibaroHC2] Configured Accessory:  VR Cuisine
[2019-5-4 20:52:44] [FibaroHC2] Configured Accessory:  VR Escalier
[2019-5-4 20:52:44] [FibaroHC2] Configured Accessory:  Detecteur fuite
[2019-5-4 20:52:44] [FibaroHC2] Configured Accessory:  Temp cellier
[2019-5-4 20:52:44] [FibaroHC2] Configured Accessory:  VR Parents Etage
[2019-5-4 20:52:44] [FibaroHC2] Configured Accessory:  Volet Chambre Coline
[2019-5-4 20:52:44] [FibaroHC2] Configured Accessory:  Lampe couloir étage
[2019-5-4 20:52:44] [FibaroHC2] Configured Accessory:  Lampe Ch. parents
[2019-5-4 20:52:44] [FibaroHC2] Configured Accessory:  Det. Fumee etage
[2019-5-4 20:52:44] [FibaroHC2] Configured Accessory:  Temp Couloir
[2019-5-4 20:52:44] [FibaroHC2] didFinishLaunching. 
[2019-5-4 20:52:47] [FibaroHC2] Loading accessories 
[2019-5-4 20:52:47] [FibaroHC2] Added/changed accessory:  Guirlande
[2019-5-4 20:52:47] [FibaroHC2] Added/changed accessory:  Freebox mini
[2019-5-4 20:52:47] [FibaroHC2] Added/changed accessory:  VR Sejour
[2019-5-4 20:52:47] [FibaroHC2] Added/changed accessory:  Volet Salle de jeu
[2019-5-4 20:52:47] [FibaroHC2] Added/changed accessory:  Volet bureau
[2019-5-4 20:52:47] [FibaroHC2] Added/changed accessory:  Lampe Etagere
[2019-5-4 20:52:47] [FibaroHC2] Added/changed accessory:  PC
[2019-5-4 20:52:47] [FibaroHC2] Added/changed accessory:  Multiprise
[2019-5-4 20:52:47] [FibaroHC2] Added/changed accessory:  Ecran PC
[2019-5-4 20:52:47] [FibaroHC2] Added/changed accessory:  Multiprise P5
[2019-5-4 20:52:47] [FibaroHC2] Added/changed accessory:  Multiprise - P6
[2019-5-4 20:52:47] [FibaroHC2] Added/changed accessory:  VR Salon
[2019-5-4 20:52:47] [FibaroHC2] Added/changed accessory:  Seche-serviettes
[2019-5-4 20:52:47] [FibaroHC2] Added/changed accessory:  VR Cuisine
[2019-5-4 20:52:47] [FibaroHC2] Added/changed accessory:  VR Escalier
[2019-5-4 20:52:47] [FibaroHC2] Added/changed accessory:  Det. Fumee etage
[2019-5-4 20:52:47] [FibaroHC2] Added/changed accessory:  Temp Couloir
[2019-5-4 20:52:47] [FibaroHC2] Added/changed accessory:  Detecteur fuite
[2019-5-4 20:52:47] [FibaroHC2] Added/changed accessory:  Temp cellier
[2019-5-4 20:52:47] [FibaroHC2] Added/changed accessory:  VR Parents Etage
[2019-5-4 20:52:48] [FibaroHC2] Added/changed accessory:  Volet Chambre Coline
[2019-5-4 20:52:48] [FibaroHC2] Added/changed accessory:  Lampe couloir étage
[2019-5-4 20:52:48] [FibaroHC2] Added/changed accessory:  Lampe Ch. parents
```

Regards,
Ludovic

**Pull request merged**
